version: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            redis:
                condition: service_healthy
        environment:
            - REDIS_URL=redis:6379

    redis:
        image: redis:alpine
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 1s
            timeout: 2s
            retries: 10
        volumes:
            - redis-data:/data

volumes:
    redis-data:
